algolia/algoliasearch-client-kotlin

README.md
Replaced scout-extended Licence badge by a more generic one.
=> Fix: Licence badge in README

src/commonTest/kotlin/suite/TestSuiteSettings.kt
Fixes #92. @aseure can you have a look at the whole test? Unless I get [the specs](https://github.com/algolia/algoliasearch-client-specs/pull/38/files#diff-5ef12c50215bec6c93882f66c93ba8abR161) wrong, it's lacking the `saveObject` call.
Also, in the response the value gets deserialized as `Int` as it is a round number. I adapted the test, but let's confirm this is the behavior we want before merging!
=>  set settings.userData field in CTS test for index settings

src/commonMain/kotlin/com/algolia/search/model/apikey/SecuredAPIKeyRestriction.kt, src/commonTest/kotlin/documentation/methods/apikey/DocGenerateAPIKey.kt, src/commonTest/kotlin/model/apikey/TestSecuredAPIKeyRestriction.kt
Solves https://github.com/algolia/algoliasearch-client-kotlin/issues/165
=> fix(restrictSources): Ensure secured API key param `restrictSources` only accepts string

src/commonMain/kotlin/com/algolia/search/dsl/rule/DSLPromotions.kt, src/commonMain/kotlin/com/algolia/search/model/rule/Promotion.kt, src/commonTest/kotlin/dsl/rule/TestDSLPromotions.kt, src/commonTest/kotlin/serialize/rule/TestConsequence.kt
=> feat(rule): expose rule.consequence.promote.objectIDs string array

build.gradle.kts, buildSrc/src/main/kotlin/Robolectric.kt, src/androidMain/kotlin/com/algolia/search/helper/Hashing.kt, src/androidTest/kotlin/helper/TestHashingAndroid.kt, src/commonTest/kotlin/helper/TestHashing.kt, src/jvmTest/kotlin/helper/TestHashingJVM.kt
Fixes https://github.com/algolia/instantsearch-android/issues/191
=> fix(client): omit all line terminators in the base64 encoder

src/commonMain/kotlin/com/algolia/search/model/response/ResponseLogs.kt
Making `IndexName` property required in `InnerQuery` to match the API requirements.
=> fix(logs): make `indexName` required in `InnerQuery`

src/androidTest/kotlin/Actual.kt, src/commonTest/kotlin/Expected.kt, src/commonTest/kotlin/suite/TestSuiteAATest.kt, src/commonTest/kotlin/suite/TestSuiteRecommendation.kt, src/jvmTest/kotlin/Actual.kt
`TestSuiteAATest` fails sometimes due to the following exception at `saveObject` step:
`java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)`
This means there is no Trust Store set for the JVM.
=> fix(CTS): override default truststore type to JKS 

CHANGELOG.md, build.gradle.kts, src/jvmMain/resources/META-INF/proguard/algoliasearch.pro
Include ProGuard rules into the artifacts and allow R8 to automatically apply them:  
* AAR: `<library-dir>/proguard.txt`
* JAR: `<library-dir>/META-INF/proguard/algoliasearch.pro`
More details: 
* https://developer.android.com/studio/build/shrink-code
* https://developer.android.com/studio/projects/android-library
=> chore(shrinker): publish ProGuard rules

src/commonMain/kotlin/com/algolia/search/client/ClientSearch.kt, src/commonMain/kotlin/com/algolia/search/helper/internal/Hashing.kt, src/commonMain/kotlin/com/algolia/search/util/internal/Base64.kt, src/commonTest/kotlin/util/TestHashing.kt, src/jvmMain/kotlin/com/algolia/search/helper/internal/Hashing.kt, src/jvmTest/kotlin/helper/TestHashingJVM.kt
As mentioned in #216:
Java Base64 implementation (`java.util.Base64`) is available only since Android [API 26](https://developer.android.com/reference/java/util/Base64).
In this PR, we use Ktor's implementation instead.
Fixes #216
=> fix: use ktor implementation of base64 encoding

src/commonMain/kotlin/com/algolia/search/dsl/rule/DSLConditions.kt
Add the missing `alternative` param in the `condition` function within the `DSLConditions`.
=> fix(rule): add missing 'alternative' param to the conditions DSL

src/commonTest/kotlin/suite/TestSuiteAPIKey.kt
Change testing annotation to make `TestSuiteAPIKey` CTS test run.
The looping behavior is already [coded](https://github.com/algolia/algoliasearch-client-kotlin/blob/9ca03914bf6f1a14bbb64823498b61a909fb5c9d/src/commonMain/kotlin/com/algolia/search/client/internal/ClientSearchImpl.kt#L92-L105).
Fixes #203
=> test(apiKeys): make the TestSuiteAPIKey test runnable

CHANGELOG.md, buildSrc/src/main/kotlin/Ktor.kt, src/commonMain/kotlin/com/algolia/search/client/ClientAccount.kt, src/commonMain/kotlin/com/algolia/search/client/internal/ClientSearchImpl.kt, src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointIndex.kt, src/commonMain/kotlin/com/algolia/search/helper/ResponseException.kt, src/commonMain/kotlin/com/algolia/search/serialize/internal/Json.kt, src/commonMain/kotlin/com/algolia/search/transport/internal/Transport.kt, src/commonTest/kotlin/configuration/TestUserAgent.kt, src/commonTest/kotlin/documentation/reference/DocPhilosophy.kt, src/commonTest/kotlin/suite/TestSuiteABTest.kt, src/commonTest/kotlin/suite/TestSuiteAPIKey.kt, src/commonTest/kotlin/suite/TestSuiteMultiCluster.kt, src/commonTest/kotlin/suite/TestSuiteRecommendation.kt, src/commonTest/kotlin/suite/TestSuiteReplaceAll.kt, src/commonTest/kotlin/suite/TestSuiteRules.kt, src/commonTest/kotlin/suite/TestSuiteSynonyms.kt
Update Ktor to [1.4.1](https://github.com/ktorio/ktor/releases/tag/1.4.1) and transitively Kotlin serialization to [1.0.0-RC2](https://github.com/Kotlin/kotlinx.serialization).
_Noticeable change:_
> `encodeDefaults` flag is now set to `false` in the default configuration for JSON, CBOR and Protocol Buffers.
=> chore: update Ktor to 1.4.1 

CHANGELOG.md, src/commonMain/kotlin/com/algolia/search/model/response/ResponseVariant.kt, src/commonTest/kotlin/documentation/guides/optimize/intent/GuideDynamicFiltering.kt, src/commonTest/kotlin/serialize/response/TestResponseVariant.kt
The type of `averageClickPosition` field in variant response structure must be `Float`.
=> fix(analytics): correct AB testing average click pos type

src/commonMain/kotlin/com/algolia/search/model/search/Personalization.kt
This PR is to fix the issue of `Personalization` deserialization in `RankingInfo`. 
Currently, all fields are required; an exception will be thrown if any of the fields are missing. We change this by making all fields nullable and adding a non-nullable variant of them.
=> fix(personalization): fields deserialization and nullability

client/src/commonMain/kotlin/com/algolia/search/model/rule/FacetValuesOrder.kt
Set `FacetValuesOrder`'s field `order` to default value `emptyList()`
=> fix: set 'order' default value to empty list

README.md
The link to the proguard rules was not working, probably because it was moved
=> fix: link to proguard file in README

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt
Add `abTestID` to the search response.
=> fix: add `abTestID` to the search response

client/src/commonMain/kotlin/com/algolia/search/configuration/internal/extension/HttpClient.kt
| Related Issue     | Fix #244 
Install ktor's logging feature only if logging level is above `LogLevel.NONE`
=> fix: logging feature install on `LogLevel.NONE`

build.gradle.kts, client/api/client.api, client/build.gradle.kts, client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationInsightsImpl.kt, client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointInsightsUser.kt
Add [binary-compatibility-validator](https://github.com/Kotlin/binary-compatibility-validator):
> The tool allows to dump binary API of a Kotlin library that is public in sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that make this change binary incompatible.
=> chore: add `binary-compatibility-validator`

client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointSearch.kt, client/src/commonMain/kotlin/com/algolia/search/model/internal/request/RequestCursor.kt
| Related Issue     | no
- use [Browse index (POST)](https://www.algolia.com/doc/rest-api/search/#browse-index-post) in while loop in browseObjects instead of [Browse index (GET)](https://www.algolia.com/doc/rest-api/search/#browse-index-get)
When use [Browse Index API](https://www.algolia.com/doc/rest-api/search/#browse-index-post) with long filter string, it returns long cursor.
As a result, `index.browseObjects` fails with error `invalid: 414 Request-URI Too Large` because `index.browseObjects` append cursor parameter in URL.
example code (which uses Index.partialUpdateObjects):
```
package algoliasearch.client.kotlin.example …
```
=> fix: use POST for subsequent browse

client/src/commonMain/kotlin/com/algolia/search/model/rule/FacetOrdering.kt
| Related Issue     | Fix #322
Sets default value `emptyMap` for `FacetOrdering.values`.
=> fix: default value for `FacetOrdering.values`

client/src/commonMain/kotlin/com/algolia/search/model/search/FacetStats.kt
`FacetStats`'s properties `average` and `sum` can be nullable; this change reflects this expected behavior.
=> fix(search): facet stats `average` and `sum` as nullable

client/src/commonMain/kotlin/com/algolia/search/client/ClientAccount.kt, client/src/commonMain/kotlin/com/algolia/search/client/internal/ClientSearchImpl.kt, client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointIndex.kt, client/src/commonMain/kotlin/com/algolia/search/exception/AlgoliaRuntimeException.kt, client/src/commonMain/kotlin/com/algolia/search/exception/internal/Throwable.kt, client/src/commonMain/kotlin/com/algolia/search/transport/internal/Transport.kt, client/src/commonTest/kotlin/configuration/TestUserAgent.kt, client/src/commonTest/kotlin/documentation/methods/synonym/DocCopySynonyms.kt, client/src/commonTest/kotlin/documentation/reference/DocPhilosophy.kt, client/src/commonTest/kotlin/suite/TestSecuredAPIKeyTools.kt, client/src/commonTest/kotlin/suite/TestSuiteABTest.kt, client/src/commonTest/kotlin/suite/TestSuiteAPIKey.kt, client/src/commonTest/kotlin/suite/TestSuiteMultiCluster.kt, client/src/commonTest/kotlin/suite/TestSuiteReplaceAll.kt, client/src/commonTest/kotlin/suite/TestSuiteRules.kt, client/src/commonTest/kotlin/suite/TestSuiteSynonyms.kt, docs/ExceptionHandling.md
| Related Issue     | Fix #312   
| Need Doc update   | yes/no
At transport layer, throws `AlgoliaRuntimeException` instances instead of Ktor's exceptions.
=> fix: transport requests to throw `AlgoliaRuntimeException`s

client/build.gradle.kts, gradle/libs.versions.toml
* Update Kotlin to `1.6.21`
* Expose `kotlinx.serialization.json` as api
=> chore: update kotlin to `1.6.21`

client-bom/build.gradle.kts, client-bom/gradle.properties, gradle/libs.versions.toml, settings.gradle.kts
Adds the possibility to use [BOM](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import):
```kotlin
dependencies {
// import Kotlin API client BOM
implementation(platform("com.algolia:algoliasearch-client-kotlin-bom:2.1.0-SNAPSHOT"))
// define dependencies without versions
implementation("com.algolia:algoliasearch-client-kotlin")
implementation("io.ktor:ktor-client-okhttp")
}
```
=> chore: add maven bom

client/src/commonMain/kotlin/com/algolia/search/transport/internal/Transport.kt
| Related Issue     | Fix #370
Coroutine's `CancellationException` is propagated when an operation is cancelled.
=> fix: propagate coroutine cancellation

client/src/commonMain/kotlin/com/algolia/search/model/rule/Consequence.kt
| Related Issue     | Fix #384 
Exclude `renderingContent` from `Consequence`'s `query`.
=> fix(rules): exclude `renderingContent` from `Consequence`'s `query`

client/src/commonMain/kotlin/com/algolia/search/model/filter/internal/Filter.kt, client/src/commonTest/kotlin/model/filter/TestFilterFacetString.kt, client/src/commonTest/kotlin/model/filter/TestFilterTag.kt
| Related Issue     | [CR-3573](https://algolia.atlassian.net/browse/CR-3573)
Adds explicit escaping for the quotation marks in the textual filters values causing a bad search request.
Duplicates the fix [#293](https://github.com/algolia/instantsearch-ios/pull/293) for InstantSearch iOS.
The input `45\"-50\" tv\'s` is transformed to `"45"-50" tv's"` and breaks the JSON format. 
[CR-3573]: https://algolia.atlassian.net/browse/CR-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(filters): issue with textual value escaping

client/src/commonMain/kotlin/com/algolia/search/dsl/DSLQuery.kt, client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt, client/src/commonMain/kotlin/com/algolia/search/model/search/Query.kt, client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Key.kt, client/src/commonTest/kotlin/Extensions.kt, client/src/commonTest/kotlin/dsl/TestDSLQuery.kt, client/src/commonTest/kotlin/serialize/search/TestQuery.kt
| New feature?      | yes   
Add basic support of `extensions` in both `Query` and `ResponseSearch` as `JsonObject`.
=> feat(search): add basic support of `extensions`

client/src/commonMain/kotlin/com/algolia/search/model/indexing/Partial.kt, client/src/commonTest/kotlin/serialize/indexing/TestPartialUpdate.kt
| Related Issue     | Fix #402
Allow `JsonElement` as parameter of `Partial.Update`, including `JsonNull` (or `JsonPrimitive(null)`).
=> fix(indexing): `JsonElement` as param of `Partial.Update`

client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Json.kt, client/src/commonTest/kotlin/serialize/TestUnicode.kt
| New feature?      | no   
| Related Issue     | CR-4434
Ktor's `formUrlEncode()`loops indefinitely when it ends with unpaired surrogates. In this PR, we address this issue by removing any unpaired surrogates from the input.
=> fix(search): unpaired surrogate url encoded query

client/src/commonMain/kotlin/com/algolia/search/model/rule/Consequence.kt, client/src/commonMain/kotlin/com/algolia/search/model/rule/OptionalFilters.kt, client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Json.kt, client/src/commonTest/kotlin/serialize/rule/TestConsequence.kt, gradle/libs.versions.toml
| Related Issue     | Fix [DI-1984] [CR-6113]
Add a new `OptionalFilters` interface with a polymorphic serializer so they can be either a list of OptionalFilters or a String
Add a new optionalFilters property in the rule `Consequence` class that is a `List<OptionalFilters>`
Rule consequence param `optionalFilters` weren't deserialized and could cause a crash if they were present in the request response
[DI-1984]: https://algolia.atlassian.net/browse/DI-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CR-6113]: https://algolia.atlassian.net/browse/CR-6113?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> fix(rule): add optional filters property to the rule consequence params

client/src/commonMain/kotlin/com/algolia/search/model/rule/FacetValuesOrder.kt, client/src/commonTest/kotlin/serialize/settings/TestFacetValuesOrder.kt
| Related Issue     | Fix [CR-6138]
`FacetValuesOrder` is now polymorphic so its `order` property can be optional
The engine can send a `FacetValuesOrder` object without an `order` property, so we weren't able to deserialize it properly
[CR-6138]: https://algolia.atlassian.net/browse/CR-6138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: enable omitting order property in FacetValuesOrder

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseListIndices.kt, client/src/commonTest/kotlin/model/response/TestResponseListIndices.kt
| Related Issue     | Fix [CR-6376] [DI-2696]
Make some props optional when deserializing list indices endpoint responses
Some props were required while the API may not always provide them
[CR-6376]: https://algolia.atlassian.net/browse/CR-6376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DI-2696]: https://algolia.atlassian.net/browse/DI-2696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(search): make some props optional when listing indices
