algolia/algoliasearch-client-kotlin

src/commonMain/kotlin/com/algolia/search/endpoint/EndpointIndex.kt
src/commonMain/kotlin/com/algolia/search/endpoint/EndpointIndexImpl.kt
src/commonTest/kotlin/suite/TestSuiteIndexExists.kt

Index exists method and test

---

src/commonTest/kotlin/suite/TestSuiteSettings.kt

fix(TestSuiteSettings): add missing saveObject

---

src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt

fix(ResponseSearch): refactor automaticRadius as String

---

src/commonTest/kotlin/suite/TestSuiteInsights.kt
src/jvmTest/kotlin/suite/TestSuiteInsights.kt

Adds timestamp to the test, also aligns objectIDs with the specs.

feat(TestSuiteInsights): Add timestamp, fixes #89

---

src/commonMain/kotlin/com/algolia/search/endpoint/EndpointSearch.kt
src/commonMain/kotlin/com/algolia/search/endpoint/EndpointSearchImpl.kt
src/commonMain/kotlin/com/algolia/search/model/response/ResponseHitWithPosition.kt
src/commonMain/kotlin/com/algolia/search/model/response/ResponseHitsWithPosition.kt
src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt
src/commonTest/kotlin/suite/TestSuiteSearch.kt
src/commonTest/resources/companies.json

Relevance helper functions

---

src/commonMain/kotlin/com/algolia/search/client/ClientSearch.kt
src/commonMain/kotlin/com/algolia/search/helper/Hashing.kt
src/commonMain/kotlin/com/algolia/search/model/apikey/APIKey.kt
src/commonTest/kotlin/suite/TestSecuredAPIKey.kt
src/jvmMain/kotlin/com/algolia/search/helper/Hashing.kt

getSecuredApiKeyRemainingValidity

---

src/commonMain/kotlin/com/algolia/search/endpoint/EndpointSearch.kt
src/commonMain/kotlin/com/algolia/search/endpoint/EndpointSearchImpl.kt
src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt
src/commonTest/kotlin/suite/TestSuiteSearch.kt

Deprecate and rename findFirstObject and getObjectIDPosition

---

src/commonTest/resources/settings.json

Internal [issue](https://github.com/algolia/algoliasearch-client-specs-internal/pull/38)

Add user data to settings CTS

---

src/commonMain/kotlin/com/algolia/search/model/rule/Condition.kt
src/commonMain/kotlin/com/algolia/search/model/rule/Rule.kt
src/commonTest/kotlin/suite/TestSuiteRules.kt
src/commonTest/resources/rule_batch.json

Contextual rules

---

src/androidTest/kotlin/suite/TestSecuredAPIKey.kt
src/commonTest/kotlin/suite/TestSuiteAATest.kt
src/commonTest/kotlin/suite/TestSuiteABTest.kt
src/commonTest/kotlin/suite/TestSuiteAPIKey.kt
src/commonTest/kotlin/suite/TestSuiteAccount.kt
src/commonTest/kotlin/suite/TestSuiteBatching.kt
src/commonTest/kotlin/suite/TestSuiteBrowse.kt
src/commonTest/kotlin/suite/TestSuiteCopyIndex.kt
src/commonTest/kotlin/suite/TestSuiteDisjunctive.kt
src/commonTest/kotlin/suite/TestSuiteHierarchical.kt
src/commonTest/kotlin/suite/TestSuiteIndexExists.kt
src/commonTest/kotlin/suite/TestSuiteIndexing.kt
src/commonTest/kotlin/suite/TestSuiteInsights.kt
src/commonTest/kotlin/suite/TestSuiteMultipleOperations.kt
src/commonTest/kotlin/suite/TestSuiteReplaceAll.kt
src/commonTest/kotlin/suite/TestSuiteRules.kt
src/commonTest/kotlin/suite/TestSuiteSearch.kt
src/commonTest/kotlin/suite/TestSuiteSettings.kt
src/commonTest/kotlin/suite/TestSuiteSynonyms.kt
src/jvmTest/kotlin/suite/TestSecuredAPIKey.kt

- There is a job on the index that cleans it every 24h
- That makes our UTs run faster

Avoid cleaning indices as it is already being done every 24h

---

CHANGELOG.md
README.md

release/1.4.0: add changelog and warning about kotlin required version

---

src/commonMain/kotlin/com/algolia/search/model/apikey/SecuredAPIKeyRestriction.kt
src/commonTest/kotlin/model/apikey/TestSecuredAPIKeyRestriction.kt

fix/restrict-source: API retrocompatibility

---

CHANGELOG.md

Update changelog to match the changes of version 1.4.0

changelog: add all changes and fixes for version 1.4.0

---

gradle/wrapper/gradle-wrapper.properties
src/commonMain/kotlin/com/algolia/search/model/insights/InsightsEvent.kt

fix(InsightsEvent): serialization in old Android JVMs

---

src/commonMain/kotlin/com/algolia/search/dsl/DSLQuery.kt
src/commonMain/kotlin/com/algolia/search/model/filter/FilterConverter.kt
src/commonMain/kotlin/com/algolia/search/model/filter/FilterGroupsConverter.kt
src/commonMain/kotlin/com/algolia/search/model/filter/FilterInternals.kt
src/commonTest/kotlin/dsl/TestDSLQuery.kt
src/commonTest/kotlin/model/filter/TestFilterFacetString.kt
src/commonTest/kotlin/model/filter/TestFilterNumericRange.kt
src/commonTest/kotlin/model/filter/TestFilterTag.kt

refact(filterConverter): add unquoted version of legacy converter

---

src/commonTest/kotlin/suite/TestSuiteRecommendation.kt

The personalization API is now limiting the number of `setPersonalizationStrategy()` successful calls
to 15 per day. If the `429` error is returned, the response is considered a _success_.
Fixes: #206

fix(personalization_strategy):  prevent error in CTS personalization test on 429 HTTP code

---

src/jvmMain/resources/META-INF/proguard/algoliasearch.pro

_Mentioned in https://github.com/algolia/algoliasearch-client-kotlin/pull/212#issuecomment-676518451_

chore(shrinker): Keep less content

---

build.gradle.kts
src/commonMain/kotlin/com/algolia/search/helper/internal/Hashing.kt
src/jvmMain/kotlin/com/algolia/search/helper/internal/Hashing.kt

Update spotless and apply ktlint code changes.

chore: update spotless to 0.39.0

---

src/commonTest/kotlin/documentation/guides/rule/GuideCustomizeSearch.kt
src/commonTest/kotlin/documentation/guides/rule/GuideDynamicFiltring.kt
src/commonTest/kotlin/documentation/guides/rule/GuideOptionalFilters.kt
src/commonTest/kotlin/documentation/guides/rule/GuidePromotingHits.kt
src/commonTest/kotlin/documentation/guides/rule/GuideTaggedQuery.kt

Add the documentation guide's Kotlin snippets to the test source code for tracking.

chore(docs): add documentation guide's Kotlin snippets

---

README.md

Update the R8/Proguard readme section to match the latest changes.

chore: update r8/proguard readme section

---

src/commonTest/kotlin/suite/TestSuiteIndexing.kt

Delete by tag CTS test:
* Save objects with a tag
* Delete those objects by the same tag

feat(cts): add delete by tag test

---

src/commonTest/kotlin/documentation/guides/optimize/intent/GuideDynamicFiltering.kt

Add api numerical filtering Kotlin snippets to match public documentation

chore(doc):api numerical filtering

---

src/commonMain/kotlin/com/algolia/search/configuration/internal/extension/HttpClient.kt
src/commonMain/kotlin/com/algolia/search/exception/AlgoliaRuntimeException.kt
src/commonMain/kotlin/com/algolia/search/transport/internal/Transport.kt

* Change the timeout logic by using Ktor's [timeout feature](https://ktor.io/docs/timeout.html#install)
* Update unreachable hosts exception to contain details of all exceptions

fix(transport): client timeout and unreachable hosts

---

src/commonMain/kotlin/com/algolia/search/transport/internal/Transport.kt
src/commonTest/kotlin/suite/TestSuiteDNS.kt

* Setup timeout as socket timeout to follow clients [specification](https://www.algolia.com/doc/api-reference/api-methods/configuring-timeouts/#method-param-readtimeout)
* Support all timeout exceptions from Ktor [timeout](https://ktor.io/docs/timeout.html#install)

fix(transport): read/write timeouts as socket timeout

---

src/commonMain/kotlin/com/algolia/search/client/ClientPlaces.kt

Remove Places client's redundant function builder and fix future conflicts with avoid Kotlin/JS

refact(places): remove redundant constructor

---

CHANGELOG.md
src/commonMain/kotlin/com/algolia/search/dsl/rule/DSLConditions.kt
src/commonMain/kotlin/com/algolia/search/model/rule/Condition.kt
src/commonTest/kotlin/serialize/rule/TestCondition.kt

| New feature?      | yes
| Related Issue     | Fix #250 
Adds filters parameter to rules condition

feat(rules): add filters param to rules condition

---

CHANGELOG.md
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Ktor.kt
buildSrc/src/main/kotlin/plugin/Spotless.kt
src/commonTest/kotlin/serialize/search/TestQuery.kt
src/commonTest/kotlin/serialize/settings/TestSettings.kt

* Kotlin 1.4.30
* Ktor 1.5.1
* Spotless 5.9.0
* Ktlint 0.50.0

chore(deps): update kotlin dependencies (1.4.30)

---

build.gradle.kts
buildSrc/build.gradle.kts

| Related Issue     | Fix #256

refact: remove bintray repository from the deps

---

README.md
gradle.properties

| Related Issue     | Fix #258 

chore(publishing): publish artifacts and guide update

---

DOCKER_README.md
Dockerfile
README.md

Add repository docker setup
Closes #237

chore(docker): add a Dockerfile and a guide to setup Docker

---

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseVariant.kt

fix(analytics): nullability in the fields of responses

---

build.gradle.kts
buildSrc/src/main/kotlin/Ktor.kt
buildSrc/src/main/kotlin/Library.kt
buildSrc/src/main/kotlin/MavenPublish.kt
buildSrc/src/main/kotlin/Spotless.kt
client/src/commonMain/kotlin/com/algolia/search/helper/internal/HexConverter.kt
client/src/commonMain/kotlin/com/algolia/search/model/rule/Edit.kt
client/src/commonTest/kotlin/documentation/methods/dictionaries/DocDictionarySaveEntry.kt
client/src/commonTest/kotlin/documentation/methods/indexing/DocAddObjects.kt
client/src/commonTest/kotlin/documentation/methods/indexing/DocCustomBatch.kt
client/src/commonTest/kotlin/documentation/methods/indexing/DocGetObjects.kt
client/src/commonTest/kotlin/documentation/methods/indexing/DocReplaceAllObjects.kt
client/src/commonTest/kotlin/documentation/methods/indexing/DocSaveObjects.kt
client/src/commonTest/kotlin/documentation/methods/search/DocSearch.kt
client/src/commonTest/kotlin/documentation/reference/DocPhilosophy.kt
client/src/commonTest/kotlin/documentation/reference/DocQuickStartIndex.kt
client/src/commonTest/kotlin/helper/TestResponseSearch.kt
client/src/commonTest/kotlin/serialize/rule/TestEdit.kt
client/src/commonTest/kotlin/suite/TestSuiteDNS.kt
client/src/commonTest/kotlin/suite/TestSuiteDictionary.kt
client/src/commonTest/kotlin/suite/TestSuiteIndexing.kt
client/src/commonTest/kotlin/suite/TestSuiteSearch.kt
client/src/jvmTest/kotlin/documentation/guides/data/GuideImportingJVM.kt

feat(kotlin): update to kotlin 1.5.0

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

chore: update kotlin to 1.5.20

---

CHANGELOG.md
buildSrc/src/main/kotlin/Ktor.kt

| Need Doc update   | yes/no
Update Ktor to [1.6.1](https://github.com/ktorio/ktor/releases/tag/1.6.1)

chore: update ktor to 1.6.1

---

build.gradle.kts
client/build.gradle.kts

chore: fix get lib version

---

client/src/commonMain/kotlin/com/algolia/search/model/rule/FacetValuesOrder.kt

fix: remove defaults from `FacetValuesOrder`

---

CHANGELOG.md
client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointAnswers.kt
client/src/commonMain/kotlin/com/algolia/search/helper/internal/Encoding.kt
client/src/commonMain/kotlin/com/algolia/search/model/IndexName.kt
client/src/commonMain/kotlin/com/algolia/search/model/dictionary/Dictionary.kt

fix(answers): use UTF8 encoded index name

---

gradle/libs.versions.toml

chore: ktor version to 1.6.2

---

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearch.kt

replace `!!` with `checkNotNull` and add kdoc
Replace `!!` with `checkNotNull` and add missing kdoc

chore: add more clarity to not nullable fields

---

build.gradle.kts
client/src/commonMain/kotlin/com/algolia/search/model/apikey/SecuredAPIKeyRestriction.kt
client/src/commonMain/kotlin/com/algolia/search/model/insights/InsightsEvent.kt
client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Json.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

* Kotlin to version `1.5.30` 
* Ktor to version `1.6.3`

chore: update kotlin to version `1.5.30`

---

CHANGELOG.md
client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointDictionary.kt
client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointRecommend.kt
client/src/commonMain/kotlin/com/algolia/search/model/recommend/RecommendationModel.kt
client/src/commonMain/kotlin/com/algolia/search/util/internal/Base64.kt
gradle.properties

fix: warnings after kotlin 1.5.30 + ktor 1.6.3 update

---

build.gradle.kts
gradle/libs.versions.toml

* Update kotlin to `1.5.31`
* Update ktor to `1.6.5`

chore: update kotlin to `1.5.31`

---

build.gradle.kts
client/build.gradle.kts
client/src/commonTest/kotlin/documentation/methods/search/DocSearch.kt

chore: update to kotlin `1.6.0`

---

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearchRules.kt
client/src/commonMain/kotlin/com/algolia/search/model/rule/Promotion.kt

| Related Issue     | Fix #315   

fix(rules): `Promotion` deserialization

---

docs/ExceptionHandling.md

Update example of catching multiple exceptions using `AlgoliaRuntimeException`.

chore: update exception handling guide

---

build.gradle.kts
gradle/libs.versions.toml

* Kotlin `1.6.10`
* Ktor `1.6.8`

chore: update to kotlin 1.6.10

---

gradle/wrapper/gradle-wrapper.properties

chore: update gradle to `7.4.2`

---

README.md

| Related Issue     | Fix #331   
- Updated DOCKER_README.MD to DOCKER_README.md
- Updated LICENSE.md to LICENSE
Broken web links in README.md

Update README.md fix issue #331

---

README.md
docs/GettingStarted.md
docs/Serialization.md
docs/guide/Migrate_1.x_2.x.md

chore: update guides for release `2.x`

---

gradle/libs.versions.toml

chore: update ktor to `2.0.2`

---

build.gradle.kts
gradle.properties

chore: update maven publish configuration

---

client/src/commonMain/kotlin/com/algolia/search/configuration/internal/extension/AlgoliaAgent.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/extension/HttpClient.kt
client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointInsights.kt
client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Key.kt
client/src/commonTest/kotlin/configuration/TestUserAgent.kt

Replace `User-Agent` header with `X-Algolia-Agent` url parameter.

fix(agent): algolia agent as query param

---

CHANGELOG.md
gradle.properties

chore: prepare next release 2.1.4

---

client/src/commonMain/kotlin/com/algolia/search/model/response/ResponseSearchForFacets.kt

fix(search): `exhaustiveFacetsCount` optional field

---

client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Json.kt

fix(serialization): ignore unknown keys

---

client/src/commonMain/kotlin/com/algolia/search/endpoint/EndpointPersonalization.kt
client/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointPersonalization.kt
client/src/commonMain/kotlin/com/algolia/search/model/personalization/DeletePersonalizationProfileResponse.kt
client/src/commonMain/kotlin/com/algolia/search/serialize/internal/Key.kt

fix(personalization): delete profile response

---

client/src/commonMain/kotlin/com/algolia/search/configuration/Configuration.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationAnalytics.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationInsights.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationPersonalization.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationPlaces.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationRecommend.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/ConfigurationSearch.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationAnalyticsImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationInsightsImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationPersonalizationImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationPlacesImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationRecommendImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/ConfigurationSearchImpl.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/Constants.kt
client/src/commonMain/kotlin/com/algolia/search/configuration/internal/extension/HttpClient.kt
gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

| Bug fix?          | yes/no
| New feature?      | yes/no    
| Related Issue     | CR-5009
Add _connect timeout_ configuration.

fix(config): add connect timeout
